### ISSUE TITLE
Opensees 3.5.0 64 bit, WARNING invalid uniaxialMaterial UVCuniaxial tag

### ISSUE THREAD

**Issue by Mohammad-Sohayeb-Akiel** [ahartloper/UVC_MatMod#16]
![image](https://github.com/ahartloper/UVC_MatMod/assets/74265872/2a75be3c-1a2f-4af9-b260-d480d8de1bed)

Hello,
Would you check this please and advise me?
I tried using the uniaxialMaterial UVCuniaxial in a new model that I am developing, but it gave me this warning. So I tried executing the truss example that you posted for the testing, same issue.

**Comment by ahartloper** [comment]
Hmm, does the model run fine if you swap out another uniaxial material?

I can look more into the issue after Aug 8 2023.

**Comment by Mohammad-Sohayeb-Akiel** [comment]
Yes. I was using the "RESSCppLab.dll" with 
"uniaxialMaterial RESSCppLab    $matTag          $E      $fy     $QInf      $b        $DInf      $a      $N        $C1       $gamma1"
It was working very well, then when I decided to use the "uniaxialMaterial UVCuniaxial" I got the error.

**Comment by Mohammad-Sohayeb-Akiel** [comment]
Hi Alex, were you able to look into this?

**Comment by ahartloper** [comment]
> Hi Alex, were you able to look into this?

Hey, I built the most recent version of OpenSees on my mac to confirm the issue. I also tried building with the previous version of the uvcUniaxial.cpp code. Same issue as you found in both cases. Needs some more time to look into.

I had no issues building and using opensees around a year ago. Another option could be to try the python interpreter version.

**Comment by Mohammad-Sohayeb-Akiel** [comment]
Perfect. I will do that.
Thanks

**Comment by ahartloper** [comment]
OK I had some time to look through the issue in detail. Looks like (seems like me) accidentally duplicated some code in a recent pull request that caused this issue. See https://github.com/OpenSees/OpenSees/pull/1269 .

I opened a new pull request on the main OpenSees repo to fix this.

In the mean time, you could clone and build my fork to get the fixed version: https://github.com/ahartloper/OpenSees/tree/fix_uvcTclCommands

You can re-open this issue if you still have problems afterwards.

**Comment by Mohammad-Sohayeb-Akiel** [comment]
I'm glad to hear that you were able to identify the source of the error. Since I've moved on to completing another chapter of my research, I'll wait to see if the issue gets resolved when I return to this. If not, I'll attempt to clone and build your fork. To be honest, I've never done this before. 
Thanks once again.

**Comment by ahartloper** [comment]
> I'm glad to hear that you were able to identify the source of the error. Since I've moved on to completing another chapter of my research, I'll wait to see if the issue gets resolved when I return to this. If not, I'll attempt to clone and build your fork. To be honest, I've never done this before. Thanks once again.

No problem, thanks for bringing it to my attention. If you have a mac I can share the compiled executable - otherwise, yes will have to wait or can get back in touch with me about building for yourself.
